<a href="https://colab.research.google.com/github/abiB27/deeplearning.ai-Assignments/blob/master/feature_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sklearn

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install tensorflow==2.0.0-beta1
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)


     |████████████████████████████████| 87.9MB 1.3MB/s 
     |████████████████████████████████| 3.1MB 35.2MB/s 
     |████████████████████████████████| 501kB 40.3MB/s 
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0
2.0.0-beta1


In [0]:
import pandas as pd

In [4]:
URL = 'https://storage.googleapis.com/applied-dl/heart.csv'

df = pd.read_csv(URL)
df.head()

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]

# Split the data

In [0]:
train, test = train_test_split(df, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)


In [7]:
len(test)

61

# pd.Dataframe to tf.Data

In [0]:
def df_to_dataset(dataframe, shuffle =True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  
  if shuffle :
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  
  return ds

In [0]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [0]:
example_batch=next(iter(train_ds))[0]

In [0]:
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

In [13]:
age = feature_column.numeric_column('age')
demo(age)

[[50.]
 [69.]
 [59.]
 [48.]
 [59.]]


In [17]:
thal = feature_column.categorical_column_with_vocabulary_list('thal',['fixed','normal','reversible'])

thal_one_hot = feature_column.indicator_column(thal)
demo(thal_one_hot)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
